light_gradient_boosting <- function(
  database,
  actual_period,
  last_batch,
  algorithm,
  min_effectif = 10){

  fields <- c(
    "siret",
    "siren",
    "periode",
    "age",
    # URSSAF
    "montant_part_patronale",
    "montant_part_ouvriere",
    "effectif",
    "effectif_entreprise",
    "effectif_consolide",
    "montant_echeancier",
    "delai",
    "duree_delai",
    # URSSAF 12m,
    "ratio_dette",
    "ratio_dette_moy12m",
    "cotisation_moy12m",
    # URSSAF past
    "montant_part_patronale_past_1",
    "montant_part_ouvriere_past_1",
    "montant_part_patronale_past_2",
    "montant_part_ouvriere_past_2",
    "montant_part_patronale_past_3",
    "montant_part_ouvriere_past_3",
    "montant_part_patronale_past_6",
    "montant_part_ouvriere_past_6",
    "montant_part_patronale_past_12",
    "montant_part_ouvriere_past_12",
    "effectif_past_6",
    "effectif_past_12",
    "effectif_past_18",
    "effectif_past_24",
    # ALTARES
    "etat_proc_collective",
    # DIANE
    "exercice_diane",
    "nom_entreprise",
    "numero_siren",
    "statut_juridique",
    "effectif_consolide",
    "dette_fiscale_et_sociale",
    "frais_de_RetD",
    "conces_brev_et_droits_sim",
    "note_preface",
    "nombre_etab_secondaire",
    "nombre_filiale",
    "taille_compo_groupe",
    "arrete_bilan_diane",
    "nombre_mois",
    "concours_bancaire_courant",
    "equilibre_financier",
    "independance_financiere",
    "endettement",
    "autonomie_financiere",
    "degre_immo_corporelle",
    "financement_actif_circulant",
    "liquidite_generale",
    "liquidite_reduite",
    "rotation_stocks",
    "credit_client",
    "credit_fournisseur",
    "ca_par_effectif",
    "taux_interet_financier",
    "taux_interet_sur_ca",
    "endettement_global",
    "taux_endettement",
    "capacite_remboursement",
    "capacite_autofinancement",
    "couverture_ca_fdr",
    "couverture_ca_besoin_fdr",
    "poids_bfr_exploitation",
    "exportation",
    "efficacite_economique",
    "productivite_potentiel_production",
    "productivite_capital_financier",
    "productivite_capital_investi",
    "taux_d_investissement_productif",
    "rentabilite_economique",
    "performance",
    "rendement_brut_fonds_propres",
    "rentabilite_nette",
    "rendement_capitaux_propres",
    "rendement_ressources_durables",
    "taux_marge_commerciale",
    "taux_valeur_ajoutee",
    "part_salaries",
    "part_etat",
    "part_preteur",
    "part_autofinancement",
    "ca",
    "ca_exportation",
    "achat_marchandises",
    "achat_matieres_premieres",
    "production",
    "marge_commerciale",
    "consommation",
    "autres_achats_charges_externes",
    "valeur_ajoutee",
    "charge_personnel",
    "impots_taxes",
    "subventions_d_exploitation",
    "excedent_brut_d_exploitation",
    "autres_produits_charges_reprises",
    "dotation_amortissement",
    "resultat_expl",
    "operations_commun",
    "produits_financiers",
    "charges_financieres",
    "interets",
    "resultat_avant_impot",
    "produit_exceptionnel",
    "charge_exceptionnelle",
    "participation_salaries",
    "impot_benefice",
    "benefice_ou_perte",
    # DIANE PAST 1
    "exercice_diane_past1",
    "nom_entreprise_past1",
    "numero_siren_past1",
    "statut_juridique_past1",
    "effectif_consolide_past1",
    "dette_fiscale_et_sociale_past1",
    "frais_de_RetD_past1",
    "conces_brev_et_droits_sim_past1",
    "note_preface_past1",
    "nombre_etab_secondaire_past1",
    "nombre_filiale_past1",
    "taille_compo_groupe_past1",
    "arrete_bilan_diane_past1",
    "nombre_mois_past1",
    "concours_bancaire_courant_past1",
    "equilibre_financier_past1",
    "independance_financiere_past1",
    "endettement_past1",
    "autonomie_financiere_past1",
    "degre_immo_corporelle_past1",
    "financement_actif_circulant_past1",
    "liquidite_generale_past1",
    "liquidite_reduite_past1",
    "rotation_stocks_past1",
    "credit_client_past1",
    "credit_fournisseur_past1",
    "ca_par_effectif_past1",
    "taux_interet_financier_past1",
    "taux_interet_sur_ca_past1",
    "endettement_global_past1",
    "taux_endettement_past1",
    "capacite_remboursement_past1",
    "capacite_autofinancement_past1",
    "couverture_ca_fdr_past1",
    "couverture_ca_besoin_fdr_past1",
    "poids_bfr_exploitation_past1",
    "exportation_past1",
    "efficacite_economique_past1",
    "productivite_potentiel_production_past1",
    "productivite_capital_financier_past1",
    "productivite_capital_investi_past1",
    "taux_d_investissement_productif_past1",
    "rentabilite_economique_past1",
    "performance_past1",
    "rendement_brut_fonds_propres_past1",
    "rentabilite_nette_past1",
    "rendement_capitaux_propres_past1",
    "rendement_ressources_durables_past1",
    "taux_marge_commerciale_past1",
    "taux_valeur_ajoutee_past1",
    "part_salaries_past1",
    "part_etat_past1",
    "part_preteur_past1",
    "part_autofinancement_past1",
    "ca_past1",
    "ca_exportation_past1",
    "achat_marchandises_past1",
    "achat_matieres_premieres_past1",
    "production_past1",
    "marge_commerciale_past1",
    "consommation_past1",
    "autres_achats_charges_externes_past1",
    "valeur_ajoutee_past1",
    "charge_personnel_past1",
    "impots_taxes_past1",
    "subventions_d_exploitation_past1",
    "excedent_brut_d_exploitation_past1",
    "autres_produits_charges_reprises_past1",
    "dotation_amortissement_past1",
    "resultat_expl_past1",
    "operations_commun_past1",
    "produits_financiers_past1",
    "charges_financieres_past1",
    "interets_past1",
    "resultat_avant_impot_past1",
    "produit_exceptionnel_past1",
    "charge_exceptionnelle_past1",
    "participation_salaries_past1",
    "impot_benefice_past1",
    "benefice_ou_perte_past1",
    # DIANE PAST 2 
    "exercice_diane_past2",
    "nom_entreprise_past2",
    "numero_siren_past2",
    "statut_juridique_past2",
    "effectif_consolide_past2",
    "dette_fiscale_et_sociale_past2",
    "frais_de_RetD_past2",
    "conces_brev_et_droits_sim_past2",
    "note_preface_past2",
    "nombre_etab_secondaire_past2",
    "nombre_filiale_past2",
    "taille_compo_groupe_past2",
    "arrete_bilan_diane_past2",
    "nombre_mois_past2",
    "concours_bancaire_courant_past2",
    "equilibre_financier_past2",
    "independance_financiere_past2",
    "endettement_past2",
    "autonomie_financiere_past2",
    "degre_immo_corporelle_past2",
    "financement_actif_circulant_past2",
    "liquidite_generale_past2",
    "liquidite_reduite_past2",
    "rotation_stocks_past2",
    "credit_client_past2",
    "credit_fournisseur_past2",
    "ca_par_effectif_past2",
    "taux_interet_financier_past2",
    "taux_interet_sur_ca_past2",
    "endettement_global_past2",
    "taux_endettement_past2",
    "capacite_remboursement_past2",
    "capacite_autofinancement_past2",
    "couverture_ca_fdr_past2",
    "couverture_ca_besoin_fdr_past2",
    "poids_bfr_exploitation_past2",
    "exportation_past2",
    "efficacite_economique_past2",
    "productivite_potentiel_production_past2",
    "productivite_capital_financier_past2",
    "productivite_capital_investi_past2",
    "taux_d_investissement_productif_past2",
    "rentabilite_economique_past2",
    "performance_past2",
    "rendement_brut_fonds_propres_past2",
    "rentabilite_nette_past2",
    "rendement_capitaux_propres_past2",
    "rendement_ressources_durables_past2",
    "taux_marge_commerciale_past2",
    "taux_valeur_ajoutee_past2",
    "part_salaries_past2",
    "part_etat_past2",
    "part_preteur_past2",
    "part_autofinancement_past2",
    "ca_past2",
    "ca_exportation_past2",
    "achat_marchandises_past2",
    "achat_matieres_premieres_past2",
    "production_past2",
    "marge_commerciale_past2",
    "consommation_past2",
    "autres_achats_charges_externes_past2",
    "valeur_ajoutee_past2",
    "charge_personnel_past2",
    "impots_taxes_past2",
    "subventions_d_exploitation_past2",
    "excedent_brut_d_exploitation_past2",
    "autres_produits_charges_reprises_past2",
    "dotation_amortissement_past2",
    "resultat_expl_past2",
    "operations_commun_past2",
    "produits_financiers_past2",
    "charges_financieres_past2",
    "interets_past2",
    "resultat_avant_impot_past2",
    "produit_exceptionnel_past2",
    "charge_exceptionnelle_past2",
    "participation_salaries_past2",
    "impot_benefice_past2",
    "benefice_ou_perte_past2",
    # APART
    "apart_heures_consommees",
    "apart_heures_autorisees",
    # SIRENE
    "code_ape",
    "code_naf",
    "activite_saisonniere",
    "productif"
    )

  date_inf <- as.Date("2015-01-01")
  date_sup <- as.Date("2017-01-01")

  raw_data <- connect_to_database(
    database,
    "Features",
    last_batch,
    date_inf = date_inf,
    date_sup = date_sup,
    algo = algorithm,
    min_effectif = min_effectif,
    fields = fields)

  current_data <- connect_to_database(
    database,
    "Features",
    last_batch,
    date_inf = actual_period %m-% months(1),
    date_sup = actual_period %m+% months(1),
    algo = algorithm,
    min_effectif = min_effectif,
    fields = fields)

  raw_data <- raw_data %>%
    objective_default_or_failure(n_months = 3, threshold = 1, lookback = 18) %>%
    set_objective("default")

  out <- feature_engineering_std(raw_data, current_data)
  raw_data <- out[[1]]
  current_data <- out[[2]]

  ref_f_e <- feature_engineering_create(raw_data)

  out <- feature_engineering_apply(ref_f_e, raw_data, current_data)

  raw_data <- out[[1]]
  current_data <- out[[2]]

  rm(out)

  h2o.init(ip = "localhost", port = 4444, min_mem_size = "2G")

  train <- as.h2o(raw_data)
  current <- as.h2o(current_data)

  train["outcome"] <- h2o.relevel(x = train["outcome"], y = "non_default")

  te_map <- h2o.target_encode_create(
    train,
    x = list(c("code_naf"), c("code_ape_niveau2"), c("code_ape_niveau3"), c("code_ape_niveau4"), c("code_ape")),
    y = "outcome")

  train <- h2o.target_encode_apply(
    train,
    x = list(c("code_naf"), c("code_ape_niveau2"), c("code_ape_niveau3"), c("code_ape_niveau4"), c("code_ape")),
    y = "outcome",
    target_encode_map = te_map,
    holdout_type = "LeaveOneOut",
    blended_avg = TRUE,
    seed = 1234)

  current <- h2o.target_encode_apply(
    current,
    x = list(c("code_naf"), c("code_ape_niveau2"), c("code_ape_niveau3"), c("code_ape_niveau4"), c("code_ape")),
    y = "outcome",
    target_encode_map = te_map,
    holdout_type = "None",
    blended_avg = FALSE,
    fold_column = "fold_column",
    noise_level = 0)

  x_medium <- c("montant_part_patronale",
    "ratio_dette",
    "ratio_dette_moy12m",
    "etat_proc_collective_num",
    "TargetEncode_code_ape_niveau3",
    "cotisation_moy12m",
    "frais_financier_distrib_APE1",
    "taux_marge_distrib_APE1",
    "montant_part_patronale_past_3",
    "ratio_liquidite_reduite_distrib_APE1",
    "dette_fiscale",
    "ratio_delai_client_distrib_APE1",
    "montant_part_patronale_past_1",
    "montant_part_patronale_past_2",
    "ratio_rend_capitaux_propres",
    "taux_marge",
    "poids_frng_distrib_APE1",
    "delai_fournisseur_distrib_APE1",
    "taux_rotation_stocks_distrib_APE1",
    "effectif",
    "ratio_rentabilite_nette_distrib_APE1",
    "ratio_export_distrib_APE1",
    "TargetEncode_code_ape_niveau2",
    "effectif_past_12",
    "montant_part_ouvriere",
    "financier_court_terme_distrib_APE1",
    #"effectif_entreprise",
    "age",
    "ratio_liquidite_reduite",
    "ratio_productivite_distrib_APE1",
    "frais_financier",
    "financier_court_terme",
    "ratio_delai_client",
    "TargetEncode_code_naf",
    "resultat_net_consolide",
    "taux_rotation_stocks",
    "nombre_etab_secondaire",
    "nbr_etablissements_connus",
    "CA",
    "chiffre_affaires_net_lie_aux_exportations",
    "ratio_dette_delai",
    "ratio_marge_operationnelle_distrib_APE1",
    "poids_frng")

  y <- "outcome"

  model <- h2o.xgboost(
    model_id = "Model_train",
    x = x_medium,
    y = y,
    training_frame = train,
    tree_method = "hist",
    grow_policy = "lossguide",
    learn_rate = 0.1,
    max_depth = 4,
    ntrees = 60,
    seed = 123
    )
  prediction <- as.tibble(h2o.cbind(current, h2o.predict(model, current)))

  prediction <- prediction %>% mutate(
    # H2O bug ??
    periode =  as.Date(structure(periode / 1000,
        class = c("POSIXct", "POSIXt")))
    ) %>%
  rename(prob = default) %>%
  select(predict, prob, siret, periode)

pred_data <- prediction %>%
  group_by(siret) %>%
  arrange(siret,periode) %>%
  mutate(last_prob = lag(prob)) %>%
  ungroup() %>%
  mutate(diff = prob - last_prob)


export_fields <-  c(
  "siret",
  "periode",
  "raison_sociale",
  "departement",
  "region",
  "prob",
  "diff",
  "connu",
  "date_ccsf",
  "etat_proc_collective",
  "date_proc_collective",
  "interessante_urssaf",
  #"default_urssaf",
  "effectif",
  "libelle_naf",
  "libelle_ape5",
  "code_ape",
  "montant_part_ouvriere",
  "montant_part_patronale",
  "CA",
  "CA_past_1",
  "resultat_net_consolide",
  "resultat_net_consolide_past_1",
  "resultat_expl",
  "resultat_expl_past_1",
  "poids_frng",
  "taux_marge",
  "frais_financier",
  "financier_court_terme",
  "delai_fournisseur",
  "dette_fiscale",
  "apart_heures_consommees",
  "apart_heures_autorisees",
  "cotisation_moy12m",
  "montant_majorations",
  "numero_compte_urssaf",
  "exercice_bdf",
  "exercice_diane"
  )

# Export
pred_data %>%
  filter(periode == actual_period) %>%
  prepare_for_export(export_fields = export_fields, database = database, last_batch = last_batch, algorithm = algorithm) %>%
  export(batch = last_batch)

# Returns H2O frames and model
return(list(train_data = train, current_data = current, model = model))
}
