---
title: "Random forest pipe"
author: "Pierre Camilleri"
date: "1 juin 2018"
output: html_document
---

## Imports
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Libraries
library(tidyverse)
library(h2o)
library(lubridate)
library(assertthat)
library(mongolite)
library(mice)
library(caret)
library(broom)
library(randomForest)
library(MLmetrics)
library(tibbletime)
library(PRROC)
library(broom)
library(rprojroot)
library(groupdata2)
library(R.utils)

sourceDirectory(find_rstudio_root_file('tools'), modifiedOnly = FALSE)
```

## Script parameters
```{r}
actual_period <- as.Date("2018-09-01")
last_batch = '1810'
algorithm = 'algo2'
```


## Recuperation des données dans MongoDB
```{r}
fields <- c(
  "siret",
  "siren",
  "periode",
  # URSSAF
  "cotisation",
  "montant_part_patronale",
  "montant_part_ouvriere",
  "effectif",
  "effectif_entreprise",
  "effectif_consolide",
  "montant_echeancier",
  "delai",
  "duree_delai",
  "numero_compte_urssaf",
  # URSSAF past
  "montant_part_patronale_past_1",
  "montant_part_ouvriere_past_1",
  "montant_part_patronale_past_2",
  "montant_part_ouvriere_past_2",
  "montant_part_patronale_past_3",
  "montant_part_ouvriere_past_3",
  "montant_part_patronale_past_6",
  "montant_part_ouvriere_past_6",
  "montant_part_patronale_past_12",
  "montant_part_ouvriere_past_12",
  "effectif_past_6",
  "effectif_past_12",
  "effectif_past_18",
  "effectif_past_24",
  # ALTARES
  "etat_proc_collective",
  # DIANE
  "CA",
  "resultat_net_consolide",
  "resultat_expl",
  "taux_marge",
  "delai_fournisseur",
  "poids_frng",
  "frais_financier",
  "financier_court_terme",
  "dette_fiscale",
  "capacite_autofinanc_avant_repartition",
  "ratio_marge_operationnelle",
  "taux_rotation_stocks",
  "ratio_productivite",
  "ratio_export",
  "ratio_delai_client",
  "liquidite_reduite",
  "rentabilite_nette_pourcent",
  "endettement_pourcent",
  "rend_des_capitaux_propres_nets_pourcent",
  "rend_des_ress_durables_nettes_pourcent",
  "clients_et_cptes_ratt",
  "frais_de_RetD",
  "produits_intermed_et_finis",
  "marchandises",
  "en_cours_de_prod_de_biens",
  "matières_prem_approv",
  "chiffre_affaires_net_lie_aux_exportations",
  # DIANE_past
  "CA_past_1",  
  "resultat_net_consolide_past_1",
  "resultat_expl_past_1",
  "taux_marge_past_1",
  "delai_fournisseur_past_1",
  "poids_frng_past_1",
  "frais_financier_past_1",
  "financier_court_terme_past_1",
  "dette_fiscale_past_1",
  "capacite_autofinanc_avant_repartition_past_1",
  "ratio_marge_operationnelle_past_1",
  "taux_rotation_stocks_past_1",
  "ratio_productivite_past_1",
  "ratio_export_past_1",
  "ratio_delai_client_past_1",
  "liquidite_reduite_past_1",
  "rentabilite_nette_pourcent_past_1",
  "endettement_pourcent_past_1",
  "rend_des_capitaux_propres_nets_pourcent_past_1",
  "rend_des_ress_durables_nettes_pourcent_past_1",
  "clients_et_cptes_ratt_past_1",
  "frais_de_RetD_past_1",
  "produits_intermed_et_finis_past_1",
  "marchandises_past_1",
  "en_cours_de_prod_de_biens_past_1",
  "matières_prem_approv_past_1",
  "chiffre_affaires_net_lie_aux_exportations_past_1",
  "CA_past_2",
  "resultat_net_consolide_past_2",
  "resultat_expl_past_2",
  "taux_marge_past_2",
  "delai_fournisseur_past_2",
  "poids_frng_past_2",
  "frais_financier_past_2",
  "financier_court_terme_past_2",
  "dette_fiscale_past_2",
  "capacite_autofinanc_avant_repartition_past_2",
  "ratio_marge_operationnelle_past_2",
  "taux_rotation_stocks_past_2",
  "ratio_productivite_past_2",
  "ratio_export_past_2",
  "ratio_delai_client_past_2",
  "liquidite_reduite_past_2",
  "rentabilite_nette_pourcent_past_2",
  "endettement_pourcent_past_2",
  "rend_des_capitaux_propres_nets_pourcent_past_2",
  "rend_des_ress_durables_nettes_pourcent_past_2",
  "clients_et_cptes_ratt_past_2",
  "frais_de_RetD_past_2",
  "produits_intermed_et_finis_past_2",
  "marchandises_past_2",
  "en_cours_de_prod_de_biens_past_2",
  "matières_prem_approv_past_2",
  "chiffre_affaires_net_lie_aux_exportations_past_2",
  "nombre_etab_secondaire",
  "nbr_etablissements_connus",
  # APART 
  "apart_heures_consommees",
  # SIRENE
  "code_ape",
  "code_naf",
  "debut_activite",
  "activite_saisonniere",
  "productif"
  )

date_inf <- as.Date("2015-01-01")
date_sup <- as.Date("2017-01-01")

raw_data <- connect_to_database(
  'Features',
  last_batch, 
  date_inf = date_inf,
  date_sup = date_sup,
  algo = algorithm, 
  min_effectif = 30,
  fields = fields)

all_data <- connect_to_database(
  'Features',
  last_batch, 
  date_inf = actual_period %m-% months(2),
  date_sup = actual_period,
  algo = algorithm,
  min_effectif = 30, 
  fields = fields)

```
## Definition de l'objectif
```{r}
raw_data <- raw_data %>%
  objective_default_or_failure(n_months = 3, threshold = 1, lookback = 18) %>%
  set_objective('default')
```

```{r}
out <- feature_engineering_std(raw_data, all_data)
raw_data <- out[[1]]
all_data <- out[[2]]

ref_f_e <- feature_engineering_create(raw_data)

out <- feature_engineering_apply(ref_f_e, raw_data, all_data)

raw_data <- out[[1]]
all_data <- out[[2]]

rm(out)
```

```{r}
gc()
h2o.init(ip = "localhost", port = 4444)

train <- as.h2o(raw_data) 
all <- as.h2o(all_data)

```

```{r}
train['outcome'] <- h2o.relevel(x = train['outcome'], y = "non_default")
```

```{r}
te_map <- h2o.target_encode_create(
  train, 
  x = list(c('code_naf'), c('code_ape_niveau2'), c('code_ape_niveau3'), c('code_ape_niveau4'), c('code_ape')),
  y = 'outcome')

train <- h2o.target_encode_apply(
  train, 
  x = list(c('code_naf'), c('code_ape_niveau2'), c('code_ape_niveau3'), c('code_ape_niveau4'), c('code_ape')),
  y = 'outcome',
  target_encode_map = te_map,
  holdout_type = 'LeaveOneOut',
  blended_avg = TRUE,
  seed = 1234)

all <- h2o.target_encode_apply(
  all,
  x = list(c('code_naf'), c('code_ape_niveau2'), c('code_ape_niveau3'), c('code_ape_niveau4'), c('code_ape')),
  y = 'outcome',
  target_encode_map = te_map, 
  holdout_type = 'None',
  blended_avg = FALSE,
  fold_column = 'fold_column',
  noise_level = 0)
```

## Model

```{r}
x_medium <- c("montant_part_patronale",                   
              "ratio_dette",                              
              "ratio_dette_moy12m",                       
              "etat_proc_collective_num",                 
              "TargetEncode_code_ape_niveau3",            
              "cotisation",                               
              "frais_financier_distrib_APE1",             
              "taux_marge_distrib_APE1",                  
              "montant_part_patronale_past_3",       
              "ratio_liquidite_reduite_distrib_APE1",     
              "dette_fiscale",                            
              "ratio_delai_client_distrib_APE1",          
              "montant_part_patronale_past_1",       
              "montant_part_patronale_past_2",       
              "ratio_rend_capitaux_propres",              
              "taux_marge",                               
              "poids_frng_distrib_APE1",                  
              "delai_fournisseur_distrib_APE1",           
              "taux_rotation_stocks_distrib_APE1",        
              "effectif",                                 
              "ratio_rentabilite_nette_distrib_APE1",     
              "ratio_export_distrib_APE1",                
              "TargetEncode_code_ape_niveau2",            
              "effectif_past_12",                      
              "montant_part_ouvriere",                    
              "financier_court_terme_distrib_APE1",       
              #"effectif_entreprise",                      
              "age",                                      
              "ratio_liquidite_reduite",                  
              "ratio_productivite_distrib_APE1",          
              "frais_financier",                          
              "financier_court_terme",                    
              "ratio_delai_client",                       
              "TargetEncode_code_naf",            
              "resultat_net_consolide",                   
              "taux_rotation_stocks",                     
              "nombre_etab_secondaire",                   
              "nbr_etablissements_connus",                
              "CA",                                       
              "chiffre_affaires_net_lie_aux_exportations",
              "ratio_dette_delai",                        
              "ratio_marge_operationnelle_distrib_APE1",  
              "poids_frng")  

y = "outcome"
```


```{r}
model <- h2o.xgboost(
                    model_id = 'Model_train',
                    x= x_medium, 
                    y =y,
                    training_frame = train,
                    tree_method = "hist",
                    grow_policy = "lossguide",
                    learn_rate = 0.1,
                    max_depth = 4,
                    ntrees = 60,
                    seed = 123
                )
```


## Prediction
```{r}

prediction <- as.tibble(h2o.cbind(all,h2o.predict(model,all)))

prediction <- prediction %>% mutate(
  periode =  as.Date(structure(periode / 1000, 
                               class = c('POSIXct','POSIXt')))
)%>%
  rename(prob = default0) 

pred_data <- all_data %>%
  left_join(prediction  %>% select(predict, prob,siret, periode), by=c('siret', 'periode')) %>% 
  group_by(siret) %>%
  arrange(siret,periode) %>% 
  mutate(last_prob = lag(prob),
         interressant_urssaf = all(tail(montant_part_ouvriere + montant_part_patronale, 6) < 2)) %>% 
  ungroup() %>% 
  mutate(diff = prob - last_prob) 

# Export
pred_data %>% 
  filter(periode == actual_period) %>% 
  prepare_for_export() %>% #additional_names = c('diff', 'connu', 'interressant_urssaf')) %>%
  export(batch = '1810')
```


## Export graphiques Shapley
```{r}
prediction_2 <-pred_data %>% 
  filter(periode == actual_period) %>% 
  prepare_for_export()

prediction <- prediction %>%
  left_join(prediction_2 %>% 
              select(siret, connu), by = 'siret') %>% 
  filter(periode == "2018-09-01")

prediction <- prediction %>%
  arrange(desc(prob)) %>% 
  filter(code_naf == "C", 
         connu == 0, 
         etat_proc_collective == "in_bonis",
         is.na(date_ccsf)) 
  
features  <- prediction[,x_medium]
response <- 2-as.numeric(as.factor(as.vector(prediction$outcome)))
pred <- function(model, newdata)  {
  results <- as.data.frame(h2o.predict(model, as.h2o(newdata)))
  return(results[[3L]])
}
```

```{r}
library(iml)
predictor.xgb <- Predictor$new(
  model = model,
  data = features,
  y = response,
  predict.fun = pred,
  class = "classification"
)
```

```{r}

for (i in 1:30){
  company_name <- as.character(prediction$raison_sociale[i])
  shap.xgb <- Shapley$new(predictor.xgb, x.interest = features[i,])

  shap_plot <- shap.xgb %>% plot()
  thresh <- 10e-5 
  to_remove <- abs(shap_plot$data[,"phi"]) < thresh
  shap_plot$data <- shap_plot$data[!to_remove,]
  

  shap_plot + theme(title = element_text(company_name))
ggsave(paste0("~/Documents/opensignauxfaibles/output/misc/shapley_", i, "_", company_name, ".png"))
    dev.off()
}
```

